### ISSUE TITLE
[Feature Request] Publish application on F-Droid, too.

### ISSUE THREAD

**Issue by muhsinkutay** [iamnijat/habitonic#3]
Information about F-Droid: 
F-Droid is a robot with a passion for Free and Open Source Software (FOSS) on the Android platform. On this site you’ll find a repository of FOSS apps, along with an Android client to perform installations and updates, news, reviews, and other features covering all things Android and software-freedom related.

To publish application on this platform:
https://f-droid.org/en/contribute/

**Comment by iamnijat** [comment]
Thank you for your advice, I will review and make research about that
